models:
  - name: bert-small-uncased-whole-word-masking-squad-0001
    launchers:
      - framework: dlsdk
        adapter:
          type: bert_question_answering
          start_token_logits_output: "output_s"
          end_token_logits_output: "output_e"
        inputs:
          - name: "input_ids"
            type: INPUT
            value: "input_ids"
          - name: "attention_mask"
            type: INPUT
            value: 'input_mask'
          - name: 'token_type_ids'
            type: INPUT
            value: 'segment_ids'

    datasets:
      - name: squad
        data_source: squad_v1.1
        annotation_conversion:
          converter: squad
          testing_file: squad_v1.1/dev-v1.1.json
          vocab_file: bert-large-uncased-whole-word-masking-squad-onnx/vocab.txt
          max_seq_length: 384
          max_query_length: 64
          doc_stride: 128
          lower_case: true
        reader:
          type: annotation_features_extractor
          features:
            - input_ids
            - input_mask
            - segment_ids
        postprocessing:
          - type: extract_answers_tokens
            max_answer: 30
            n_best_size: 20
        metrics:
          - name: 'F1'
            type: 'f1'
          - name: 'EM'
            type: 'exact_match'
