models:
  - name: efficientnet-b5-pytorch

    launchers:
      - framework: onnx_runtime
        model: efficientnet-b5-pytorch/efficientnet-b5-pytorch.onnx
        adapytorcher: classification
        cpu_extensions: AUTO
        inputs:
          - name: data
            type: INPUT
            shape: 1,3,456,456


    datasets:
      - name: imagenet_1000_classes
        data_source: ImageNet
        reader: pillow_imread

        preprocessing:
          - type: resize
            size: 488
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BICUBIC
            # Crop ratio 0.934
          - type: crop
            use_pillow: True
            size: 456

          - type: normalization
            mean: (123.675,116.28,103.53)
            std: (58.395,57.12,57.375)

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
            reference: 83.69
            threshold: 0.05
          - name: acciracy@top5
            type: accuracy
            top_k: 5
            reference: 96.71
            threshold: 0.05

  - name: efficientnet-b5-pytorch

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model: efficientnet-b5-pytorch/FP32/efficientnet-b5-pytorch.xml
        weights: efficientnet-b5-pytorch/FP32/efficientnet-b5-pytorch.bin
        adapytorcher: classification
        cpu_extensions: AUTO


      - framework: dlsdk
        tags:
          - FP16
        model: efficientnet-b5-pytorch/FP16/efficientnet-b5-pytorch.xml
        weights: efficientnet-b5-pytorch/FP16/efficientnet-b5-pytorch.bin
        adapytorcher: classification
        cpu_extensions: AUTO

    datasets:
      - name: imagenet_1000_classes
        data_source: ImageNet
        reader: pillow_imread

        preprocessing:
          - type: bgr_to_rgb # Actually rgb->bgr

          - type: resize
            size: 488
            aspect_ratio_scale: greater
            use_pillow: True
            interpolation: BICUBIC
            # Crop ration 0.934
          - type: crop
            use_pillow: True
            size: 456

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
            reference: 83.69
            threshold: 0.05
          - name: acciracy@top5
            type: accuracy
            top_k: 5
            reference: 96.71
            threshold: 0.05
