models:
  - name: efficientnet-b7_auto_aug

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/efficientnet-b7_auto_aug-tf/FP32/efficientnet-b7_auto_aug-tf.xml
        weights: public/efficientnet-b7_auto_aug-tf/FP32/efficientnet-b7_auto_aug-tf.bin
        adapter: classification
        cpu_extensions: AUTO

      - framework: dlsdk
        tags:
          - FP16
        model:   public/efficientnet-b7_auto_aug-tf/FP16/efficientnet-b7_auto_aug-tf.xml
        weights: public/efficientnet-b7_auto_aug-tf/FP16/efficientnet-b7_auto_aug-tf.bin
        adapter: classification
        cpu_extensions: AUTO

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
        - type: crop
          central_fraction: 0.875
          use_pillow: True
        - type: resize
          size: 600
          use_pillow: True
          interpolation: BICUBIC
