models:
  - name: face-detection-0101

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   intel/face-detection-0101/FP32/face-detection-0101.xml
        weights: intel/face-detection-0101/FP32/face-detection-0101.bin
        adapter:
          type: fcos_person
          scale: 0.00347222222

    datasets:
      - name: wider

        preprocessing:
          - type: resize
            size: 288

        postprocessing:
          - type: resize_prediction_boxes
          - type: cast_to_int
          - type: clip_boxes
            size: 1024
            apply_to: annotation
          - type: filter
            apply_to: annotation
            height_range: 64, 1024
            is_empty: True

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: True
            distinct_conf: False

global_definitions: ../dataset_definitions.yml
