models:
  - name: style_transfer
    launchers:
      - framework: onnx_runtime
        device: CPU
        model: public/fast-neural-style-mosaic-onnx/fast-neural-style-mosaic-onnx.onnx
        adapter: style_transfer

      - framework: dlsdk
        tags:
          - FP32
        model: public/fast-neural-style-mosaic-onnx/FP32/fast-neural-style-mosaic-onnx.xml
        weights: public/fast-neural-style-mosaic-onnx/FP32/fast-neural-style-mosaic-onnx.bin
        adapter: style_transfer
      - framework: dlsdk
        tags:
          - FP16
        model: public/fast-neural-style-mosaic-onnx/FP16/fast-neural-style-mosaic-onnx.xml
        weights: public/fast-neural-style-mosaic-onnx/FP16/fast-neural-style-mosaic-onnx.bin
        adapter: style_transfer

    datasets:
      - name: coco_style_transfer

global_definitions: ../dataset_definitions.yml
