models:
  - name: midasnet

    launchers:
      - framework: onnx_runtime
        model: public/midasnet/midasnet.onnx
        adapter: mono_depth
        inputs:
          - name: image
            type: INPUT
            shape: 1,3,384,384

    datasets:
      - name: redweb
        reader: scipy_imread

        preprocessing:
          - type: resize
            dst_width: 384
            dst_height: 384
            interpolation: Cubic
          
          - type: normalization
            std: 255

  - name: midasnet

    # list of launchers for MidasNet.
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/midasnet/FP32/midasnet.xml
        weights: public/midasnet/FP32/midasnet.bin
        adapter: mono_depth
      
      - framework: dlsdk
        tags:
          - FP16
        model:   public/midasnet/FP16/midasnet.xml
        weights: public/midasnet/FP16/midasnet.bin
        adapter: mono_depth

    datasets:
      - name: redweb
        reader: opencv_imread

        preprocessing:          
          - type: resize
            dst_width: 384
            dst_height: 384
            interpolation: Cubic

          - type: normalization
            std: 255
