models:
  - name: mono-depth
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        # path to IR relative to open_model_zoo/models for FP32/FP16 converted precisions
        model: mono-depth.xml
        weights: mono-depth.bin
        adapter: mono_depth
    datasets:
      - name: ReDWeb_V1
        # data_source, annotation_conversion and annotation should be moved to dataset_definitions.yml
        data_source: ReDWeb_V1
        annotation_conversion:
          converter: redweb
          data_dir: RedWeb_V1
        annotation: mono_depth.pickle
        preprocessing:
          - type: resize
            size: 384
        postprocessing:
          - type: resize_prediction_depth_map
          - type: align_prediction_depth_map
        metrics:
          - type: rmse

global_definitions: ../dataset_definitions.yml
