models:
  - name: midasnet
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        # path to IR relative to open_model_zoo/models for FP32/FP16 converted precisions
        model: /code/open_model_zoo/tools/downloader/public/midasnet/FP32/midasnet.xml
        weights: /code/open_model_zoo/tools/downloader/public/midasnet/FP32/midasnet.bin
        adapter: mono_depth
    datasets:
      - name: ReDWeb_V1
        preprocessing:
          - type: resize
            size: 384
        postprocessing:
          - type: resize_prediction_depth_map
          - type: align_prediction_depth_map
        metrics:
          - type: rmse

global_definitions: ../dataset_definitions.yml
