models:
  - name: style_transfer

    launchers:

      - framework: onnx_runtime
        device: CPU
        model: public/mosaic/mosaic.onnx
        adapter: style_transfer

      - framework: dlsdk
        tags:
          - FP32
        model: public/mosaic/FP32/mosaic.xml
        weights: public/mosaic/FP32/mosaic.bin
        adapter: style_transfer
        
      - framework: dlsdk
        tags:
          - FP16
        model: public/mosaic/FP16/mosaic.xml
        weights: public/mosaic/FP16/mosaic.bin
        adapter: style_transfer

    datasets:
      - name: coco_style_transfer

global_definitions: ../dataset_definitions.yml
