models:
  - name: peleenet_coco

    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   peleenet_coco/FP32/peleenet_coco.xml
        weights: peleenet_coco/FP32/peleenet_coco.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model:   peleenet_coco/FP16/peleenet_coco.xml
        weights: peleenet_coco/FP16/peleenet_coco.bin
        adapter: ssd

    datasets:
      - name: ms_coco_detection_80_class_with_backgound

        preprocessing:
          - type: resize
            dst_width: 304
            dst_height: 304

        postprocessing:
          - type: resize_prediction_boxes

        metrics:
          - type: coco_precision
            max_detections: 100

global_definitions: ../dataset_definitions.yml
