models:
  - name: resnet-50-official
    launchers:
      - framework: tf
        model: public/resnet-50-official/resnet_v1-50.pb
        adapter: classification
        inputs:
          - name: map/TensorArrayStack/TensorArrayGatherV3
            type: INPUT

    datasets:
      - name: imagenet_1001_classes
        preprocessing:
          - type: bgr_to_rgb
          - type: normalization
            mean: [123.68, 116.78, 103.94]
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224


  - name: resnet-50-official
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model:   public/resnet-50-official/FP32/resnet-50-official.xml
        weights: public/resnet-50-official/FP32/resnet-50-official.bin
        adapter: classification

      - framework: dlsdk
        tags:
          - FP16
        model:   public/resnet-50-official/FP16/resnet-50-official.xml
        weights: public/resnet-50-official/FP16/resnet-50-official.bin
        adapter: classification

    datasets:
      - name: imagenet_1001_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224

global_definitions: ../dataset_definitions.yml
