models:
  - name: retinanet-tf
    launchers:
      - framework: dlsdk
        tags:
          - FP32
        model: public/retinanet-tf/FP32/retinanet-tf.xml
        weights: public/retinanet-tf/FP32/retinanet-tf.bin
        adapter: ssd

      - framework: dlsdk
        tags:
          - FP16
        model: public/retinanet-tf/FP16/retinanet-tf.xml
        weights: public/retinanet-tf/FP16/retinanet-tf.bin
        adapter: ssd

    datasets:
      - name: ms_coco_detection_80_class_without_backgound
        preprocessing:
          - type: resize
            aspect_ratio_scale: frcnn_keep_aspect_ratio
            dst_height: 1333
            dst_width: 1333
          - type: padding
            dst_height: 1333
            dst_width: 1333
            pad_type: right_bottom

        postprocessing:
          - type: faster_rcnn_postprocessing_resize
            dst_height: 1333
            dst_width: 1333

        metrics:
          - type: map
            integral: 11point
            presenter: print_scalar

          - type: coco_precision

global_definitions: ../dataset_definitions.yml
